import type { AnalysisResult, PricingRecommendation, QuoteCalculation, QuoteBuilderState } from '@/types'

function fmt(n: number): string {
  return n.toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })
}

export function generateQuoteSummary(
  analysis: AnalysisResult,
  recommendation: PricingRecommendation,
  quote: QuoteCalculation,
  quoteState: QuoteBuilderState
): string {
  const lines: string[] = []

  lines.push('='.repeat(60))
  lines.push('ACE™ MANAGED ACCESSIBILITY — QUOTE SUMMARY')
  lines.push('AccessibilityChecker.org')
  lines.push('='.repeat(60))
  lines.push('')
  lines.push(`Client Domain:    ${analysis.domain}`)
  lines.push(`Platform:         ${analysis.platform} (${analysis.platformConfidence} confidence)`)
  lines.push(`Date:             ${new Date(analysis.analyzedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`)
  lines.push('')
  lines.push('SITE ANALYSIS')
  lines.push('-'.repeat(40))
  lines.push(`Raw Pages Scanned:      ${analysis.rawPageCount.toLocaleString()}`)
  lines.push(`Template Types:         ${analysis.templateTypesCount}`)
  lines.push(`Content Pages:          ${analysis.contentPagesCount.toLocaleString()}`)
  lines.push(`Unique Pages:           ${analysis.uniquePagesCount}`)
  lines.push(`Dynamic Pages:          ${analysis.dynamicPagesCount}`)
  lines.push(`Weighted Page Count:    ${analysis.weightedPageCount.toLocaleString()}`)
  lines.push('')
  lines.push('PAGE CATEGORIES')
  lines.push('-'.repeat(40))
  for (const cat of analysis.categories) {
    const padding = ' '.repeat(Math.max(0, 24 - cat.category.length))
    lines.push(`${cat.category}:${padding}${cat.rawCount.toLocaleString()} raw → ${cat.weightedCount.toLocaleString()} weighted (${cat.typeLabel})`)
  }
  lines.push('')
  lines.push('RECOMMENDED PLAN')
  lines.push('-'.repeat(40))

  if (recommendation.weightedPlan) {
    lines.push(`Plan:             ${recommendation.weightedPlan.name}`)
    lines.push(`Max Pages:        Up to ${recommendation.weightedPlan.maxWeightedPages.toLocaleString()} weighted pages`)
    lines.push(`Monthly Price:    ${fmt(recommendation.monthlyPrice)}/mo`)
    lines.push(`Annual Price:     ${fmt(recommendation.annualPrice)}/yr`)
  } else {
    lines.push('Plan:             Requires custom Enterprise quote')
  }

  lines.push('')
  lines.push('SAVINGS COMPARISON')
  lines.push('-'.repeat(40))
  if (recommendation.rawPlan) {
    lines.push(`Without weighted pricing: ${recommendation.rawPlan.name} (${fmt(recommendation.rawMonthlyPrice)}/mo)`)
    lines.push(`With weighted pricing:    ${recommendation.weightedPlan?.name ?? 'Custom'} (${fmt(recommendation.monthlyPrice)}/mo)`)
    lines.push(`Weight Reduction:         ${recommendation.weightReductionPercent}% fewer effective pages`)
    lines.push(`Annual Savings:           ${fmt(recommendation.annualSavings)}/yr`)
  }

  if (quoteState.dedicatedTeam || quoteState.extraDomains > 0 || quoteState.extraPdfPages > 0 || quoteState.additionalVpats > 0) {
    lines.push('')
    lines.push('ADD-ONS')
    lines.push('-'.repeat(40))
    if (quoteState.extraDomains > 0) {
      lines.push(`Extra Domains (${quoteState.extraDomains}):  ${fmt(quote.extraDomainCost)}/mo`)
    }
    if (quoteState.dedicatedTeam) {
      lines.push(`Dedicated Team:           ${fmt(quote.dedicatedTeamCost)}/mo`)
    }
    if (quoteState.extraPdfPages > 0) {
      lines.push(`Extra PDF Pages (${quoteState.extraPdfPages}):    ${fmt(quote.oneTimePdfCost)} one-time`)
    }
    if (quoteState.additionalVpats > 0) {
      lines.push(`Additional VPATs (${quoteState.additionalVpats}):   ${fmt(quote.oneTimeVpatCost)} one-time`)
    }
  }

  lines.push('')
  lines.push('QUOTE TOTALS')
  lines.push('-'.repeat(40))
  lines.push(`Monthly Total:    ${fmt(quote.monthlyTotal)}/mo`)
  lines.push(`Annual Total:     ${fmt(quote.annualTotal)}/yr`)
  if (quote.totalOneTime > 0) {
    lines.push(`One-Time Fees:    ${fmt(quote.totalOneTime)}`)
    lines.push(`Year 1 Total:     ${fmt(quote.yearOneTotal)}`)
  }

  if (quoteState.notes) {
    lines.push('')
    lines.push('NOTES')
    lines.push('-'.repeat(40))
    lines.push(quoteState.notes)
  }

  lines.push('')
  lines.push('='.repeat(60))
  lines.push('Generated by ACE™ Sitemap Page Classifier')
  lines.push('AccessibilityChecker.org — Internal Tool')
  lines.push('='.repeat(60))

  return lines.join('\n')
}
