import type { ManagedPlan, PageWeights } from '@/types'

export const DEFAULT_WEIGHTS: PageWeights = {
  template: 1.0,
  unique: 1.0,
  content: 0.2,
  dynamic: 1.2,
}

export const MANAGED_PLANS: ManagedPlan[] = [
  {
    name: 'Small Sites',
    maxWeightedPages: 25,
    monthlyPrice: 599,
    annualPrice: 7188,
    auditFrequency: 'Semi-Annual',
    defaultPdfPages: 10,
    vpatIncluded: '1/year',
    teamDefault: 'By Our Devs',
  },
  {
    name: 'Medium Sites',
    maxWeightedPages: 100,
    monthlyPrice: 949,
    annualPrice: 11388,
    auditFrequency: 'Quarterly',
    defaultPdfPages: 25,
    vpatIncluded: '1/year',
    teamDefault: 'By Our Devs',
  },
  {
    name: 'Large Sites',
    maxWeightedPages: 500,
    monthlyPrice: 1249,
    annualPrice: 14988,
    auditFrequency: 'Quarterly',
    defaultPdfPages: 50,
    vpatIncluded: '1/year',
    teamDefault: 'By Our Devs',
  },
  {
    name: 'Scale',
    maxWeightedPages: 1000,
    monthlyPrice: 1749,
    annualPrice: 20988,
    auditFrequency: 'Quarterly',
    defaultPdfPages: 100,
    vpatIncluded: '1/year',
    teamDefault: 'By Our Devs',
  },
  {
    name: 'Enterprise S',
    maxWeightedPages: 1500,
    monthlyPrice: 2199,
    annualPrice: 26388,
    auditFrequency: 'Monthly',
    defaultPdfPages: 150,
    vpatIncluded: '2/year',
    teamDefault: 'By Our Devs',
  },
  {
    name: 'Enterprise M',
    maxWeightedPages: 2000,
    monthlyPrice: 2599,
    annualPrice: 31188,
    auditFrequency: 'Monthly',
    defaultPdfPages: 200,
    vpatIncluded: '2/year',
    teamDefault: 'By Our Devs',
  },
  {
    name: 'Enterprise L',
    maxWeightedPages: 2500,
    monthlyPrice: 2999,
    annualPrice: 35988,
    auditFrequency: 'Monthly',
    defaultPdfPages: 250,
    vpatIncluded: '2/year',
    teamDefault: 'By Our Devs',
  },
  {
    name: 'Enterprise XL',
    maxWeightedPages: 5000,
    monthlyPrice: 4499,
    annualPrice: 53988,
    auditFrequency: 'Monthly',
    defaultPdfPages: 500,
    vpatIncluded: '2/year',
    teamDefault: 'By Our Devs',
  },
  {
    name: 'Enterprise 2XL',
    maxWeightedPages: 7500,
    monthlyPrice: 5499,
    annualPrice: 65988,
    auditFrequency: 'Monthly',
    defaultPdfPages: 750,
    vpatIncluded: '2/year',
    teamDefault: 'By Our Devs',
  },
  {
    name: 'Enterprise 3XL',
    maxWeightedPages: 10000,
    monthlyPrice: 6499,
    annualPrice: 77988,
    auditFrequency: 'Monthly',
    defaultPdfPages: 1000,
    vpatIncluded: '2/year',
    teamDefault: 'By Our Devs',
  },
  {
    name: 'Enterprise 4XL',
    maxWeightedPages: 15000,
    monthlyPrice: 7999,
    annualPrice: 95988,
    auditFrequency: 'Monthly',
    defaultPdfPages: 1500,
    vpatIncluded: '2/year',
    teamDefault: 'By Our Devs',
  },
  {
    name: 'Enterprise 5XL',
    maxWeightedPages: 20000,
    monthlyPrice: 9499,
    annualPrice: 113988,
    auditFrequency: 'Monthly',
    defaultPdfPages: 2000,
    vpatIncluded: '2/year',
    teamDefault: 'By Our Devs',
  },
  {
    name: 'Enterprise 6XL',
    maxWeightedPages: 30000,
    monthlyPrice: 11999,
    annualPrice: 143988,
    auditFrequency: 'Monthly',
    defaultPdfPages: 2500,
    vpatIncluded: '2/year',
    teamDefault: 'By Our Devs',
  },
  {
    name: 'Enterprise 7XL',
    maxWeightedPages: 50000,
    monthlyPrice: 15999,
    annualPrice: 191988,
    auditFrequency: 'Monthly',
    defaultPdfPages: 3500,
    vpatIncluded: '2/year',
    teamDefault: 'By Our Devs',
  },
]

export const ADD_ONS = {
  // Monthly add-on per additional domain (beyond the first) — 15% of base plan monthly
  extraDomainPercentOfBase: 0.15,
  // Monthly upgrade to a named/dedicated dev team
  dedicatedTeamMonthly: 1500,
  // One-time per extra PDF page remediated beyond plan default
  extraPdfPageOneTime: 3,
  // One-time per additional VPAT beyond plan default
  additionalVpatOneTime: 500,
}

export const WHATS_INCLUDED = [
  'Full platform access (scanning, monitoring, AI-assisted fixes)',
  'Code-level remediation by our development team',
  'Manual expert audits at the plan frequency',
  'Annual VPAT / WCAG conformance report',
  'Default PDF pages remediated per plan',
  'Ongoing support, reporting, and compliance guidance',
  'ADA / Section 508 / WCAG 2.2 AA coverage',
]
